import seaborn as sns
import matplotlib.pyplot as plt
penguins=sns.load_dataset("penguins")
print("Here are some sample penguin data:")
print(penguins.head())
species_count=penguins['species'].value_counts()
print("\nNumber of penguins in Each species:")
print(species_count)
plt.figure(figsize=(6,4))
plt.bar(species_count.index,species_count.values,color=["skyblue","salmon","lightgreen"])
plt.title("Number of penguins in each species(Matplotib)")
plt.xlabel("Penguin Species")
plt.ylabel("Count")
plt.show()
plt.figure(figsize=(6,4))
sns.countplot(x="species",data=penguins,palette="pastel")
plt.title("Penguin Species Count(Seaborn)")
plt.xlabel("Penguin Species")
plt.ylabel("Count")
plt.show()